apiVersion: v1
appVersion: 1.0.9
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: mood-feed-test
version: 1.0.9
