# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: mood-feed-test
  repository: file://../mood-feed-test
